### ISSUE TITLE
Error: Avatar buffer validation failed in Group.update()

### ISSUE THREAD

**Issue by burakgarci** [dawalters1/wolf.js#167]
https://github.com/dawalters1/wolf.js/blob/3f45d9d9c9b2b185ccdcff8f3f7872bd9fa858d0/src/helper/group/Group.js#LL259C37-L259C37

Hi,

I encountered an error while using the API. Below are the details of the error:

```
Error: avatar must be a valid buffer
    at Group.update (file:///.../myBot/node_modules/wolf.js/src/helper/group/Group.js:260:15)
    at WOLF.<anonymous> (file:///.../myBot/index.js:20:17)
    at WOLF.emit (node:events:513:28)
    at fininaliseConnection (file:///.../myBot/node_modules/wolf.js/src/client/websocket/events/welcome/WELCOME.js:28:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async login (file:///.../myBot/node_modules/wolf.js/src/client/websocket/events/welcome/WELCOME.js:70:10)
    at async default (file:///.../myBot/node_modules/wolf.js/src/client/websocket/events/welcome/WELCOME.js:93:80)
    
Param: {avatar: Buffer(1186786)}
```

Description:
I received the error message above while trying to update the avatar using the Group.update() method in my bot. The error states that the avatar provided must be a valid buffer. However, I have ensured that the avatar parameter is indeed a buffer with a size of 1186786 bytes and is already working when updating the subscriber avatar.

Steps to Reproduce:
1. Initialize the bot.
2. Call the Group.update() method with the provided avatar buffer.

Expected Behavior:
The Group.update() method should successfully update the avatar with the provided buffer.

Actual Behavior:
The method throws an error indicating that the avatar must be a valid buffer, even though I have passed a buffer object of the correct size and mime type.

Additional Information:
- Node.js version: v18.12.1
- wolf.js version: v2.0.2

Please let me know if there are any further details or steps needed to investigate and resolve this issue. Thank you!

**Comment by dawalters1** [comment]
Fixed in 2.0.7
