### ISSUE TITLE
[Channel Member] The canPerformGroupAction function always returns False ?

### ISSUE THREAD

**Issue by fawazorg** [dawalters1/wolf.js#184]
This get False even the bot is having Admin 
```js
await client.utility.subscriber.privilege.has(client.currentSubscriber.id, Privilege.GROUP_ADMIN)
```
It might be like this:
```js
await client.utility.channel.member.hasCapability(client.currentSubscriber.id,Capability.ADMIN)
```

**Comment by dawalters1** [comment]
Your client id would not have GAP privileges.

**Comment by dawalters1** [comment]
Check against guardian bot and GAP will return true.

**Comment by fawazorg** [comment]
```js
await client.channel.member.mod( command.targetChannelId, member.id);
```      
```bash
Error: Insufficient privileges to mod
    at Member.mod (file:///home/fawaz/Dev/wolf.js/src/helper/channel/Member.js:458:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/fawaz/Dev/wolf-support-bot/support/kick/index.js:65:17
    at async default (file:///home/fawaz/Dev/wolf-support-bot/support/kick/index.js:55:17)
    at async Module.default (file:///home/fawaz/Dev/wolf-support-bot/commands/kick.js:29:3) 
param: { targetChannelId: 18404568, subscriberId: 82496444 }
```
The bot have an Admin CAP in the channel!

**Comment by dawalters1** [comment]
What capability is the source account, and the target account.

**Comment by dawalters1** [comment]
This has literally been tested in the integration tests before 2.x was released

**Comment by dawalters1** [comment]
2.2.1
